pg_face_theme="fluorescent" # folder name in plugins/jarvis-face/faces/
pg_face_anim_start=true # enable animation when Jarvis is started
pg_face_anim_listening=true # enable animation when listening for command
pg_face_anim_speaking=true # enable animation when speaking
pg_face_anim_done=true # enable happy animation when conversation is over
pg_face_anim_exit=true # enable animation when Jarvis terminates
pg_face_size="" # empty for gif size, 800x450 for fixed size (use for fullscreen)
pg_face_backdrop=false # true to display fullscreen black backdrop
pg_face_x_offset="+0" # +X: Xpx from left, -X: Xpx from right (only for empty gif size)
pg_face_y_offset="+0" # +Y: Ypx from top, -Y: Ypx from bottom (only for empty gif size)
pg_face_hide_cursor=false # true to hide mouse pointer when not moved
pg_face_display_num=":0" # sometimes is :1, find using `w` command, TTY column
